---

- name: Create download directory
  file:
    path: ~/.dietpi
    state: directory

- name: Download dietpi image "{{ dietpi }}"
  get_url:
    url: "{{ dietpi }}"
    dest: "~/.dietpi/dietpi.img.xz"

- name: Extract dietpi download to ~/.dietpi/
  shell:
    cmd: unar ~/.dietpi/dietpi.img.xz
    chdir: ~/.dietpi/

- name: Get dietpi image filename
  find:
    paths: "~/.dietpi/"
    patterns: "*.img"
  register: image_files

- name: Print the img filename
  debug:
    msg: "DietPi image file found: {{ image_files.files[0].path }}"

- name: Flash SD card `balena local flash {{ image_files.files[0].path }} --drive {{ disk }} --yes`
  become: yes
  shell:
    cmd: balena local flash {{ image_files.files[0].path }} --drive {{ disk }} --yes
  register: balena_status

- name: Replace dietpi.txt
  copy:
    src: dietpi/dietpi.txt
    dest: "/Volumes/NO NAME/dietpi.txt"
    remote_src: no

- name: Deleted extracted image file
  file:
    state: absent
    path: "{{ image_files.files[0].path }}"
